spring:
  main:
    show-banner: true
  activemq:
#    broker-url: tcp://vm1:32768      
#        broker-url: failover:(tcp://192.168.66.22:61616,tcp://192.168.66.26:61616)
        broker-url: failover:(tcp://localhost:61616)  # Адрес message broker для обмена сообщениями
server:
    port: 8888   # здесь слушает http-server
    session-timeout: 5
    tomcat:
        uri-encoding: UTF-8
        max-threads: 200
camel.springboot:
  duration-max-seconds: 0  # время работы в сек 0 - бесконечно
  duration-max-messages: 0 # число Camel сообщений до окончания работы

producer-mq: activemq:amqtester.inout  # запись имя очереди для тестирования нагрузки
consumer-mq: activemq:amqtester.inout?concurrentConsumers=5 # имя очереди на чтение тестирование нагрузки
msg-period: 1000  # частота генерации сообщений в миллисекундах
client-mq: activemq:amqtester.Client  # очередь на запись клиентских запросов
operator-mq: activemq:amqtester.Operator  # очередь на запись запросов Оператора

my:
   bufSize: 50  # размер сообщения для нагруз тестирования
   loop: 10  # каждое сообщение будет размножено на i-сообщений
   producer: true # утитилита будет работать как источник сообщений
   consumer: true # утилита будет читать сообщения
# это список случайно выбираемых фамилий клиентов
   clients:
     - Ivanov
     - Sidorov
     - Петрофф
     - Антонофф
     - Маятникофф
# это список случайно выбираемых фамилий операторов
   operators:
     - Kosarev
     - Bebutoff
     - Londo
     - Капица
# это список случайно выбираемых номеров моб телефонов
   mobiles:
     - 79165806655
     - 79098887766
     - 00911122339
     - 87634565432
     - 94783648593
# ----------- end of config